updates/improvments
pguth/install-invoiceninja pull request #1
Opened 2016-11-02 18:15 UTC by fentas

some additional information within install process.

2016-11-24 16:48 UTC, perguth requested changes

2016-11-24 16:48 UTC, pguth commented on README.md
> +# If u see "Installer corrupt" it could be that composer-setup is changed.
# If you see "Installer corrupt" the `composer-setup.php` file may have been updated.

2016-11-27 15:52 UTC, fentas commented
I revised README.md

2016-11-27 17:06 UTC, perguth approved these changes

2016-11-27 17:07 UTC, merged